# Generated by Django 5.1.2 on 2025-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название опроса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('total_completions', models.PositiveIntegerField(default=0, verbose_name='Количество прохождений')),
                ('questions', models.JSONField(verbose_name='Вопросы')),
                ('completions', models.JSONField(default=list, verbose_name='Прохождения')),
            ],
        ),
    ]
