# Generated by Django 5.1.2 on 2025-01-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_survey_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='assigned_users',
            field=models.JSONField(default=list, verbose_name='Назначенные пользователи'),
        ),
    ]
