# Generated by Django 5.1.2 on 2025-01-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_survey_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='completions',
            field=models.JSONField(default=list, null=True, verbose_name='Прохождения'),
        ),
    ]
