# Generated by Django 5.1.2 on 2025-01-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_survey_completions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='completions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Прохождения'),
        ),
    ]
