# Generated by Django 5.1.2 on 2025-01-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_survey_age_survey_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='age',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='position',
        ),
    ]
